CREATE TABLE IF NOT EXISTS COFFEES(
COFFEE_ID	INTEGER NOT NULL PRIMARY KEY,
COFFEE_NAME	VARCHAR(30),
SUPPLIER_ID	INTEGER,
PRICE		FLOAT,
SALES		FLOAT,
TOTAL		FLOAT,
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
                      ON DELETE CASCADE)
ENGINE=INNODB;